stone:
  id: 1
  texture: 0,0
  tool: pickaxe
  tool.only: true
  destroy.time: 7.5
  drop: 7

dirt:
  id: 2
  texture: 1,0
  tool: shovel
  destroy.time: 0.75
  
dirt.grass:
  id: 3
  texture: 2,0
  tool: shovel
  destroy.time: 0.75
  
oak.log:
  id: 4
  texture: 3,0
  tool: axe
  destroy.time: 3
  
sand:
  id: 5
  texture: 0,1
  tool: shovel
  gravity: true
  destroy.time: 0.75
  
gravel:
  id: 6
  texture: 1,1
  tool: shovel
  gravity: true
  destroy.time: 0.9
  
cobblestone:
  id: 7
  texture: 2,1
  tool: pickaxe
  tool.only: true
  destroy.time: 10
  
oak.leaves:
  id: 8
  texture: 3,1
  tool: scissors
  tool.only: true
  destroy.time: 0.3
  
furnace:
  id: 9
  texture: 0,2
  tool: pickaxe
  tool.only: true
  collide: false
  animated.active: furnace_active
  destroy.time: 17.5
  
workbench:
  id: 10
  texture: 1,2
  tool: axe
  collide: false
  destroy.time: 3.75
  
grass:
  id: 11
  texture: 2,2
  tool: scissors
  tool.only: true
  collide: false
  map:
    floating: false
  light:
    transparency: true
  destroy.time: 0.1
  
oak.planks:
  id: 12
  texture: 3,2
  tool: axe
  destroy.time: 3
  
ore.coal:
  id: 13
  texture: 0,3
  tool: pickaxe
  tool.only: true
  destroy.time: 15
  
ore.metal:
  id: 14
  texture: 1,3
  tool: pickaxe
  tool.only: true
  destroy.time: 15
  
torch:
  id: 15
  texture: 2,3
  light:
    source: true
    transparency: true
  collide: false
  animated: torch
  destroy.time: 0.1

cactus:
  id: 16
  texture: 4,0
  map:
    floating: false
  light:
    transparency: true
  destroy.time: 0.6
    
glass:
  id: 17
  texture: 4,1
  light:
    transparency: true
  destroy.time: 0.45
 
fire:
  id: 18
  texture: 4,3
  light:
    source: true
    transparency: true
  collide: false
  animated: fire
  destroy.time: 0.1
