oak.planks:
  size: 1,1
  receipt: 4
  result:
    id: 12
    count: 4

workbench:
  size: 2,2
  receipt: 12,12,12,12
  result:
    id: 10
    count: 1
      
furnace:
  size: 3,3
  receipt: 7,7,7,7,0,7,7,7,7
  result:
    id: 9
    count: 1   
